### ISSUE TITLE
Go Incognito Premium Hosting

### ISSUE THREAD

**Issue by techlore-official** [techlore-official/go-incognito#8]
Hosting premium version of Go Incognito is still an early thing to think about, but it's coming sooner than we think. 

Current platforms in mind:

- Udemy
- Skillshare

Posting this here to keep the idea fresh and also offer discussion if there's any about it.

**Comment by ChaseHall** [comment]
+1 on skillshare, they have great course management (so ive heard) so that should make it nice for you to push content.

**Comment by beerisgood** [comment]
SSL Report: [www.udemy.com](https://www.ssllabs.com/ssltest/analyze.html?d=www.udemy.com): A+

SSL Report: [www.skillshare.com](https://www.ssllabs.com/ssltest/analyze.html?d=www.skillshare.com): B

Results for [www.udemy.com](https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fwww.udemy.com%2F):
HTTPS by default:  Yes
Content Security Policy:  Not implemented / Reports leaked
Referrer Policy:  Referrers leaked
Cookies: 48 (33 first-party; 15 third-party)
Third-party requests: 120 requests to 33 unique hosts
Server location:  United States of America

Results for [www.skillshare.com](https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fwww.skillshare.com%2F):
HTTPS by default:  Yes
Content Security Policy:  Not implemented / Reports leaked
Referrer Policy:  Referrers partially leaked
Cookies: 40 (30 first-party; 10 third-party)
Third-party requests: 147 requests to 35 unique hosts
Server location:  United States of America

**Comment by techlore-official** [comment]
Teachable was the final platform chosen.
